apiVersion: v1
kind: Namespace
metadata:
  name: frontend
---
# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deployment # Deployment 이름 구분
  namespace: frontend
  labels:
    app: frontend-app # Deployment 라벨
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app # Pod 선택용 selector
  template:
    metadata:
      labels:
        app: frontend-app # Pod 라벨
    spec:
      containers:
        - name: frontend-container
          image: jimin980915/contest-18-image-frontend:fe-{BUILD_DATE_TIME} # CI/CD 치환
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: '500m'
              memory: '512Mi'
            requests:
              cpu: '200m'
              memory: '256Mi'
---
# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-app-svc # Service 이름 구분
  namespace: frontend
spec:
  selector:
    app: frontend-app # Deployment Pod 라벨과 매칭
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
# frontend-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-app-ingress # Ingress 이름 구분
  namespace: frontend
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # SPA 루트 경로
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-app-svc
                port:
                  number: 80
