export const mockPortfolio = [
  {
    id: 1,
    title: '로컬잇 프로젝트 어쩌고',
    summary: '간단한 설명이 여기에 적혀요...',
    contribution: null,
    tag: null,
    mainCategory: null,
    subCategory: null,
    positionName: '디자이너',
    createdAt: '2025-10-26T14:34:47.117189',
  },
  {
    id: 2,
    title: '로컬잇 프로젝트 어쩌고',
    summary: '',
    contribution: 67,
    mainCategory: '공모전/대회',
    subCategory: '융합 프로젝트',
    tag: '로컬잇',
    positionName: '백엔드 개발자',
    createdAt: '2025-10-26T14:34:47.117189',
  },
  {
    id: 3,
    title: '로컬잇 프로젝트 어쩌고',
    summary: '',
    contribution: 67,
    mainCategory: '공모전/대회',
    subCategory: '융합 프로젝트',
    tag: '로컬잇',
    positionName: '기획자',
    createdAt: '2025-10-26T14:34:47.117189',
  },
  {
    id: 4,
    title: '로컬잇 프로젝트 어쩌고',
    summary: '',
    contribution: 67,
    mainCategory: '공모전/대회',
    subCategory: '융합 프로젝트',
    tag: '로컬잇',
    positionName: '백엔드 개발자',
    createdAt: '2025-10-26T14:34:47.117189',
  },
  {
    id: 5,
    title: '로컬잇 프로젝트 어쩌고',
    summary: '',
    contribution: 67,
    mainCategory: '공모전/대회',
    subCategory: '융합 프로젝트',
    tag: '로컬잇',
    positionName: '마케터',
    createdAt: '2025-10-26T14:34:47.117189',
  },
  {
    id: 6,
    title: '로컬잇 프로젝트 어쩌고',
    summary: '',
    contribution: 67,
    mainCategory: '공모전/대회',
    subCategory: '융합 프로젝트',
    tag: '로컬잇',
    positionName: '마케터',
    createdAt: '2025-10-26T14:34:47.117189',
  },
  {
    id: 7,
    title: '로컬잇 프로젝트 어쩌고',
    summary: '',
    contribution: 67,
    mainCategory: '공모전/대회',
    subCategory: '융합 프로젝트',
    tag: '로컬잇',
    positionName: '마케터',
    createdAt: '2025-10-26T14:34:47.117189',
  },
  {
    id: 8,
    title: '로컬잇 프로젝트 어쩌고',
    summary: '',
    contribution: 67,
    mainCategory: '공모전/대회',
    subCategory: '융합 프로젝트',
    tag: '로컬잇',
    positionName: '마케터',
    createdAt: '2025-10-26T14:34:47.117189',
  },
  {
    id: 9,
    title: '로컬잇 프로젝트 어쩌고',
    summary: '',
    contribution: 67,
    mainCategory: '공모전/대회',
    subCategory: '융합 프로젝트',
    tag: '로컬잇',
    positionName: '마케터',
    createdAt: '2025-10-26T14:34:47.117189',
  },
  {
    id: 10,
    title: '로컬잇 프로젝트 어쩌고',
    summary: '',
    contribution: 67,
    mainCategory: '공모전/대회',
    subCategory: '융합 프로젝트',
    tag: '로컬잇',
    positionName: '마케터',
    createdAt: '2025-10-26T14:34:47.117189',
  },
  {
    id: 11,
    title: '로컬잇 프로젝트 어쩌고',
    summary: '',
    contribution: 67,
    mainCategory: '공모전/대회',
    subCategory: '융합 프로젝트',
    tag: '로컬잇',
    positionName: '마케터',
    createdAt: '2025-10-26T14:34:47.117189',
  },
  {
    id: 12,
    title: '로컬잇 프로젝트 어쩌고',
    summary: '',
    contribution: 67,
    mainCategory: '공모전/대회',
    subCategory: '융합 프로젝트',
    tag: '로컬잇',
    positionName: '마케터',
    createdAt: '2025-10-26T14:34:47.117189',
  },
  {
    id: 13,
    title: '로컬잇 프로젝트 어쩌고',
    summary: '',
    contribution: 67,
    mainCategory: '공모전/대회',
    subCategory: '융합 프로젝트',
    tag: '로컬잇',
    positionName: '마케터',
    createdAt: '2025-10-26T14:34:47.117189',
  },
]
