name: Deploy

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VITE_API_USER_URL: ${{ secrets.VITE_API_USER_URL }}
      VITE_API_RECRUIT_URL: ${{ secrets.VITE_API_RECRUIT_URL }}
      VITE_API_BOARD_URL: ${{ secrets.VITE_API_BOARD_URL }}
      VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
      VITE_REDIRECT_URL: ${{ secrets.VITE_REDIRECT_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build app
        run: |
          export VITE_API_USER_URL=${VITE_API_USER_URL}
          export VITE_API_RECRUIT_URL=${VITE_API_RECRUIT_URL}
          export VITE_API_BOARD_URL=${VITE_API_BOARD_URL}
          export VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
          export VITE_REDIRECT_URL=${VITE_REDIRECT_URL}
          pnpm build
