name: Deploy

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 👇 추가: Google Client ID 값 찍기
      - name: Check Google Client ID
        run: echo "VITE_GOOGLE_CLIENT_ID is $VITE_GOOGLE_CLIENT_ID"
        env:
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}

      - name: Build app
        run: pnpm build
        env:
          VITE_API_USER_URL: ${{ secrets.VITE_API_USER_URL }}
          VITE_API_RECRUIT_URL: ${{ secrets.VITE_API_RECRUIT_URL }}
          VITE_API_BOARD_URL: ${{ secrets.VITE_API_BOARD_URL }}
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_REDIRECT_URL: ${{ secrets.VITE_REDIRECT_URL }}
